import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({users}) {

  const handle=async (e,x)=>{
    e.preventDefault()
     await fetch(`http://localhost:3000/api/user/${x}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({name:'Nikola', email:'nikola@gmail.com'}) // body data type must match "Content-Type" header
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        users?.map((user)=><p key={user.id}>{user.name}</p>)
      }
    <button type='button' onClick={(e)=>handle(e,2)}>Promeni Coveka</button>
    </div>
  )
}

export async  function getServerSideProps  (){
  const users = await fetch("http://localhost:3000/api/users")
  return {
    props: {users: await users.json()}
  }
}
